--- #YAML:1.0
name:               IO-Tty
version:            1.09_01
abstract:           Pseudo ttys and constants
author:
    - Roland Giersig <RGiersig@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:  {}
resources:
    repository:  https://expectperl.svn.sourceforge.net/svnroot/expectperl/IO-Tty/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
