name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
      - run: perl Makefile.PL
      - run: make
      - run: make test
      - run: sudo make install

  # ------------------------------------------------------------------------

  linux:
    name: "linux ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
            "5.14",
          ]

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
      - run: perl Makefile.PL
      - run: make
      - run: make test
      - run: make install

  # ------------------------------------------------------------------------

  BSDs:
    needs: [ubuntu, linux]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '14.2'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker

          - name: openbsd
            version: '7.6'
            pkginstall: true

          - name: netbsd
            version: '10.1'
            pkginstall: pkgin -y install perl || true

    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.32.0
        timeout-minutes: 15
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure .
            perl Makefile.PL
            make
            prove -wlvmb t

  # ------------------------------------------------------------------------

  macOS:
    runs-on: macOS-latest
    needs: [ubuntu]

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v4
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - run: make
      - run: make test
